###################################################################

# Created by write_sdc on Mon Aug 3 07:18:49 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions -max scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -max_library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -min scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -min_library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c
set_wire_load_model -name tsmc13_wl30 -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports ALU_Enable]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {ALU_FUN[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {ALU_FUN[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {ALU_FUN[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {ALU_FUN[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {ALU_A[7]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {ALU_A[6]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {ALU_A[5]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {ALU_A[4]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {ALU_A[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {ALU_A[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {ALU_A[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {ALU_A[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {ALU_B[7]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {ALU_B[6]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {ALU_B[5]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {ALU_B[4]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {ALU_B[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {ALU_B[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {ALU_B[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {ALU_B[0]}]
set_load -pin_load 50 [get_ports ALU_VLD]
set_load -pin_load 50 [get_ports {ALU_OUT[15]}]
set_load -pin_load 50 [get_ports {ALU_OUT[14]}]
set_load -pin_load 50 [get_ports {ALU_OUT[13]}]
set_load -pin_load 50 [get_ports {ALU_OUT[12]}]
set_load -pin_load 50 [get_ports {ALU_OUT[11]}]
set_load -pin_load 50 [get_ports {ALU_OUT[10]}]
set_load -pin_load 50 [get_ports {ALU_OUT[9]}]
set_load -pin_load 50 [get_ports {ALU_OUT[8]}]
set_load -pin_load 50 [get_ports {ALU_OUT[7]}]
set_load -pin_load 50 [get_ports {ALU_OUT[6]}]
set_load -pin_load 50 [get_ports {ALU_OUT[5]}]
set_load -pin_load 50 [get_ports {ALU_OUT[4]}]
set_load -pin_load 50 [get_ports {ALU_OUT[3]}]
set_load -pin_load 50 [get_ports {ALU_OUT[2]}]
set_load -pin_load 50 [get_ports {ALU_OUT[1]}]
set_load -pin_load 50 [get_ports {ALU_OUT[0]}]
create_clock [get_ports CLK]  -name MASTER_CLK  -period 50  -waveform {0 25}
set_clock_latency 0  [get_clocks MASTER_CLK]
set_clock_uncertainty -setup 0.2  [get_clocks MASTER_CLK]
set_clock_uncertainty -hold 0.1  [get_clocks MASTER_CLK]
set_clock_transition -max -rise 0.05 [get_clocks MASTER_CLK]
set_clock_transition -min -rise 0.05 [get_clocks MASTER_CLK]
set_clock_transition -max -fall 0.05 [get_clocks MASTER_CLK]
set_clock_transition -min -fall 0.05 [get_clocks MASTER_CLK]
create_generated_clock [get_pins U0_ClkDiv/o_div_clk]  -name ALU_CLK  -source [get_ports CLK]  -master_clock MASTER_CLK  -divide_by 2  -add
set_clock_uncertainty -setup 0.2  [get_clocks ALU_CLK]
set_clock_uncertainty -hold 0.1  [get_clocks ALU_CLK]
group_path -name INOUT  -from [list [get_ports CLK] [get_ports RST] [get_ports ALU_Enable] [get_ports {ALU_FUN[3]}] [get_ports {ALU_FUN[2]}] [get_ports {ALU_FUN[1]}] [get_ports {ALU_FUN[0]}] [get_ports {ALU_A[7]}] [get_ports {ALU_A[6]}] [get_ports {ALU_A[5]}] [get_ports {ALU_A[4]}] [get_ports {ALU_A[3]}] [get_ports {ALU_A[2]}] [get_ports {ALU_A[1]}] [get_ports {ALU_A[0]}] [get_ports {ALU_B[7]}] [get_ports {ALU_B[6]}] [get_ports {ALU_B[5]}] [get_ports {ALU_B[4]}] [get_ports {ALU_B[3]}] [get_ports {ALU_B[2]}] [get_ports {ALU_B[1]}] [get_ports {ALU_B[0]}]]  -to [list [get_ports ALU_VLD] [get_ports {ALU_OUT[15]}] [get_ports {ALU_OUT[14]}] [get_ports {ALU_OUT[13]}] [get_ports {ALU_OUT[12]}] [get_ports {ALU_OUT[11]}] [get_ports {ALU_OUT[10]}] [get_ports {ALU_OUT[9]}] [get_ports {ALU_OUT[8]}] [get_ports {ALU_OUT[7]}] [get_ports {ALU_OUT[6]}] [get_ports {ALU_OUT[5]}] [get_ports {ALU_OUT[4]}] [get_ports {ALU_OUT[3]}] [get_ports {ALU_OUT[2]}] [get_ports {ALU_OUT[1]}] [get_ports {ALU_OUT[0]}]]
group_path -name INREG  -from [list [get_ports CLK] [get_ports RST] [get_ports ALU_Enable] [get_ports {ALU_FUN[3]}] [get_ports {ALU_FUN[2]}] [get_ports {ALU_FUN[1]}] [get_ports {ALU_FUN[0]}] [get_ports {ALU_A[7]}] [get_ports {ALU_A[6]}] [get_ports {ALU_A[5]}] [get_ports {ALU_A[4]}] [get_ports {ALU_A[3]}] [get_ports {ALU_A[2]}] [get_ports {ALU_A[1]}] [get_ports {ALU_A[0]}] [get_ports {ALU_B[7]}] [get_ports {ALU_B[6]}] [get_ports {ALU_B[5]}] [get_ports {ALU_B[4]}] [get_ports {ALU_B[3]}] [get_ports {ALU_B[2]}] [get_ports {ALU_B[1]}] [get_ports {ALU_B[0]}]]
group_path -name REGOUT  -to [list [get_ports ALU_VLD] [get_ports {ALU_OUT[15]}] [get_ports {ALU_OUT[14]}] [get_ports {ALU_OUT[13]}] [get_ports {ALU_OUT[12]}] [get_ports {ALU_OUT[11]}] [get_ports {ALU_OUT[10]}] [get_ports {ALU_OUT[9]}] [get_ports {ALU_OUT[8]}] [get_ports {ALU_OUT[7]}] [get_ports {ALU_OUT[6]}] [get_ports {ALU_OUT[5]}] [get_ports {ALU_OUT[4]}] [get_ports {ALU_OUT[3]}] [get_ports {ALU_OUT[2]}] [get_ports {ALU_OUT[1]}] [get_ports {ALU_OUT[0]}]]
set_input_delay -clock ALU_CLK  20  [get_ports ALU_Enable]
set_input_delay -clock ALU_CLK  20  [get_ports {ALU_FUN[3]}]
set_input_delay -clock ALU_CLK  20  [get_ports {ALU_FUN[2]}]
set_input_delay -clock ALU_CLK  20  [get_ports {ALU_FUN[1]}]
set_input_delay -clock ALU_CLK  20  [get_ports {ALU_FUN[0]}]
set_input_delay -clock ALU_CLK  20  [get_ports {ALU_A[7]}]
set_input_delay -clock ALU_CLK  20  [get_ports {ALU_A[6]}]
set_input_delay -clock ALU_CLK  20  [get_ports {ALU_A[5]}]
set_input_delay -clock ALU_CLK  20  [get_ports {ALU_A[4]}]
set_input_delay -clock ALU_CLK  20  [get_ports {ALU_A[3]}]
set_input_delay -clock ALU_CLK  20  [get_ports {ALU_A[2]}]
set_input_delay -clock ALU_CLK  20  [get_ports {ALU_A[1]}]
set_input_delay -clock ALU_CLK  20  [get_ports {ALU_A[0]}]
set_input_delay -clock ALU_CLK  20  [get_ports {ALU_B[7]}]
set_input_delay -clock ALU_CLK  20  [get_ports {ALU_B[6]}]
set_input_delay -clock ALU_CLK  20  [get_ports {ALU_B[5]}]
set_input_delay -clock ALU_CLK  20  [get_ports {ALU_B[4]}]
set_input_delay -clock ALU_CLK  20  [get_ports {ALU_B[3]}]
set_input_delay -clock ALU_CLK  20  [get_ports {ALU_B[2]}]
set_input_delay -clock ALU_CLK  20  [get_ports {ALU_B[1]}]
set_input_delay -clock ALU_CLK  20  [get_ports {ALU_B[0]}]
set_output_delay -clock ALU_CLK  20  [get_ports ALU_VLD]
set_output_delay -clock ALU_CLK  20  [get_ports {ALU_OUT[15]}]
set_output_delay -clock ALU_CLK  20  [get_ports {ALU_OUT[14]}]
set_output_delay -clock ALU_CLK  20  [get_ports {ALU_OUT[13]}]
set_output_delay -clock ALU_CLK  20  [get_ports {ALU_OUT[12]}]
set_output_delay -clock ALU_CLK  20  [get_ports {ALU_OUT[11]}]
set_output_delay -clock ALU_CLK  20  [get_ports {ALU_OUT[10]}]
set_output_delay -clock ALU_CLK  20  [get_ports {ALU_OUT[9]}]
set_output_delay -clock ALU_CLK  20  [get_ports {ALU_OUT[8]}]
set_output_delay -clock ALU_CLK  20  [get_ports {ALU_OUT[7]}]
set_output_delay -clock ALU_CLK  20  [get_ports {ALU_OUT[6]}]
set_output_delay -clock ALU_CLK  20  [get_ports {ALU_OUT[5]}]
set_output_delay -clock ALU_CLK  20  [get_ports {ALU_OUT[4]}]
set_output_delay -clock ALU_CLK  20  [get_ports {ALU_OUT[3]}]
set_output_delay -clock ALU_CLK  20  [get_ports {ALU_OUT[2]}]
set_output_delay -clock ALU_CLK  20  [get_ports {ALU_OUT[1]}]
set_output_delay -clock ALU_CLK  20  [get_ports {ALU_OUT[0]}]
